CREATE DATABASE TP_FabricaRuedas;
GO
USE TP_FabricaRuedas;
GO

CREATE TABLE Areas(
	IdArea INT PRIMARY KEY IDENTITY(1,1),
	NombreArea VARCHAR(50) NOT NULL UNIQUE,
);

CREATE TABLE Empleados(
    IdEmpleado INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(100) NOT NULL,
    Apellido VARCHAR(100) NOT NULL,
    Legajo INT UNIQUE NOT NULL,
    FechaIngreso DATE NOT NULL,
	Telefono VARCHAR(20) NOT NULL,
    Cargo VARCHAR(50) NOT NULL,
    IdArea INT FOREIGN KEY REFERENCES Areas(IdArea),   
    IdSupervisor INT NULL FOREIGN KEY REFERENCES Empleados(IdEmpleado)
); 

CREATE TABLE Proveedores(
	IdProveedor INT PRIMARY KEY IDENTITY(1,1),
	NombreEmpresa VARCHAR(100) NOT NULL,
	Cuit VARCHAR(20) NOT NULL,
	Email VARCHAR(50) NOT NULL
);

CREATE TABLE Suministros(
	IdSuministro INT PRIMARY KEY IDENTITY(1,1),
	IdProveedor INT FOREIGN KEY REFERENCES Proveedores(IdProveedor),
	Descripcion VARCHAR(100) NOT NULL,
	CantdRecibida INT NOT NULL,
	FechaEntrega DATE DEFAULT GETDATE()
);

CREATE TABLE StockRuedas(
	IdRueda INT PRIMARY KEY IDENTITY(1,1),
	Modelo VARCHAR(50) NOT NULL,
	Medida VARCHAR(20) NOT NULL,
	CantDisponible INT DEFAULT (0),
	PrecioUnitario DECIMAL(18,2) NOT NULL
);

CREATE TABLE Clientes(
	IdCliente INT PRIMARY KEY IDENTITY(1,1),
	NombreCliente VARCHAR(50) NOT NULL,
	Cuit VARCHAR(20) UNIQUE,
	Telefono VARCHAR(20) NOT NULL,
	Mail VARCHAR(50) NOT NULL,
	Domicilio VARCHAR(50) NOT NULL,
	CondicionFiscal VARCHAR(20) NOT NULL
);

CREATE TABLE Ventas(
	IdVenta INT PRIMARY KEY IDENTITY(1,1),
	IdCliente INT FOREIGN KEY REFERENCES Clientes(IdCliente),
	FechaVenta DATETIME DEFAULT GETDATE(),
	MontoTotal DECIMAL(18,2) NOT NULL
);

CREATE TABLE DetalleVentas(
    IdDetalle INT PRIMARY KEY IDENTITY(1,1),
	IdVenta INT FOREIGN KEY REFERENCES Ventas(IdVenta),
	IdRueda INT FOREIGN KEY REFERENCES StockRuedas(IdRueda),
	Cantidad INT NOT NULL,
	PrecioUnitario DECIMAL(18,2) NOT NULL
);